name: ci/cd

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  testing:
    runs-on: ubuntu-22.04
    env:
      retarus_userid: ${{ secrets.RETARUS_USERID }}
      retarus_fax_password: ${{ secrets.RETARUS_FAX_PASSWORD }}
      retarus_customer_number: ${{ secrets.RETARUS_CUSTOMER_NUMBER }}
      retarus_fax_number: ${{ secrets.RETARUS_FAX_NUMBER }}
      topic: ${{ secrets.TOPIC }}
      retarus_polling_user: ${{ secrets.RETARUS_POLLING_USER }}
      retarus_polling_password: ${{ secrets.RETARUS_POLLING_PASSWORD }}
      retarus_topic_user: ${{ secrets.RETARUS_TOPIC_USER }}
      retarus_topic_password: ${{ secrets.RETARUS_TOPIC_PASSWORD }}
    strategy:
      matrix:
        python-version: ["3.10"]


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: install packages
        run: |
          pip install .

      - name: Test with pytest
        run: |
          pytest tests/testing.py
          pytest tests/test_fax_in_poll.py
          pytest tests/test.py

  building:
    needs: testing
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install requirements
        run: pip install -r requirements.txt

      - name: build package
        run: |
         pip install build 
         python3 -m build --sdist --wheel --outdir dist/ .

        if: github.ref == 'refs/heads/master'
      - uses: actions/upload-artifact@v2
        with:
          path: dist
          name: ${{ github.sha }}-ci_python_fax
