name: Publish to PyPI

on:
  push:
    tags:
      - "*"


jobs:
  building:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: install requirements
        run: pip install -r requirements.txt

      - name: build package
        run: |
         pip install build 
         python3 -m build --sdist --wheel --outdir dist/ .
      - uses: actions/cache@v3
        with:
          path: dist
          key: gh_action_retarus_sdk_python

  deploy:
    needs: building
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/cache@v3
        with:
          path: dist
          key: gh_action_retarus_sdk_python
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PIPY_API_TOKEN }}
